// // import type { Metadata } from "next";
// // import "./globals.css";  // Make sure your global styles are correctly linked
// // import Header from "@/components/Nav";
// // import Footer from "@/components/Footer";
// // import { CartProvider } from "@/context/CartContext";
// // import { WishlistProvider } from "@/context/WishlistContext";
// // import { AuthProvider } from "@/context/AuthContext";
// // import TopHeader from "@/components/Header";

// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({
// //   children,
// // }: Readonly<{
// //   children: React.ReactNode;
// // }>) {
// //   return (
// //     <html lang="en">
// //       <body className="antialiased">
// //         {/* Wrap the application in all providers */}
// //         <AuthProvider>
// //           <WishlistProvider>
// //             <CartProvider>
// //               <TopHeader />
// //               <Header />
// //               {children}
// //               <Footer />
// //             </CartProvider>
// //           </WishlistProvider>
// //         </AuthProvider>
// //       </body>
// //     </html>
// //   );
// // }



// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Header from "@/components/Nav";
// import Footer from "@/components/Footer";
// import { CartProvider } from "@/context/CartContext";
// import { WishlistProvider } from "@/context/WishlistContext"; // Import WishlistProvider
// import { AuthProvider } from "@/context/AuthContext"; // Import AuthProvider
// import TopHeader from "@/components/Header";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={${geistSans.variable} ${geistMono.variable} antialiased}
//       >
//         {/* Wrap the application in all providers */}
//         <AuthProvider>
//           <WishlistProvider>
//             <CartProvider>
//               <TopHeader/>
//               <Header />
//               {children}
//               <Footer />
//             </CartProvider>
//           </WishlistProvider>
//         </AuthProvider>
//       </body>
//     </html>
//   );
// // }   


// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Header from "@/components/Nav";
// import Footer from "@/components/Footer";
// import { CartProvider } from "@/context/CartContext";
// import { WishlistProvider } from "@/context/WishlistContext"; // Import WishlistProvider
// import { AuthProvider } from "@/context/AuthContext"; // Import AuthProvider
// import TopHeader from "@/components/Header";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {/* Wrap the application in all providers */}
//         <AuthProvider>
//           <WishlistProvider>
//             <CartProvider>
//               <TopHeader />
//               <Header />
//               {children}
//               <Footer />
//             </CartProvider>
//           </WishlistProvider>
//         </AuthProvider>
//       </body>
//     </html>
//   );
// }












import type { Metadata } from "next";
import { Roboto, Roboto_Mono } from "next/font/google"; // Use valid Google fonts
import "./globals.css";
import Header from "@/components/Nav";
import Footer from "@/components/Footer";
import { CartProvider } from "@/context/CartContext";
import { WishlistProvider } from "@/context/WishlistContext"; // Import WishlistProvider
import { AuthProvider } from "@/context/AuthContext"; // Import AuthProvider
import TopHeader from "@/components/Header";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "700"], // Specify weights as per your design
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
  weight: ["400", "700"], // Specify weights as per your design
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${robotoMono.variable} antialiased`}
      >
        {/* Wrap the application in all providers */}
        <AuthProvider>
          <WishlistProvider>
            <CartProvider>
              <TopHeader />
              <Header />
              {children}
              <Footer />
            </CartProvider>
          </WishlistProvider>
        </AuthProvider>
      </body>
    </html>
  );
}

